spring:
  h2:
    console:
      enabled: true
      settings:
        trace: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:pagatododb;MODE=PostgreSQL